<?php 
/*------------------------------------------------------------------------
# com_yeeditor - YEEditor
# ------------------------------------------------------------------------
# author    Yeedeen
# copyright Copyright (C) 2013 yeedeen.com. All Rights Reserved.
# @license - http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
# Websites: http://yeedeen.com
# Technical Support: Support - http://yeedeen.com/support/
-------------------------------------------------------------------------*/

//You can find the setting and value in the '$element_param' varible. 
defined( '_JEXEC' ) or die;
$type_attrbute="";
$output="";

if(isset($element_param['type_attrbute']))
	$type_attrbute=$element_param['type_attrbute'];

$option_value=array (
  '' => 'None',
  'icon-adjust' => 'Adjust',
  'icon-align-center' => 'Align-center',
  'icon-align-justify' => 'Align-justify',
  'icon-align-left' => 'Align-left',
  'icon-align-right' => 'Align-right',
  'icon-arrow-down' => 'Arrow-down',
  'icon-arrow-left' => 'Arrow-left',
  'icon-arrow-right' => 'Arrow-right',
  'icon-arrow-up' => 'Arrow-up',
  'icon-asterisk' => 'Asterisk',
  'icon-backward' => 'Backward',
  'icon-ban-circle' => 'Ban-circle',
  'icon-barcode' => 'Barcode',
  'icon-bell' => 'Bell',
  'icon-bold' => 'Bold',
  'icon-book' => 'Book',
  'icon-bookmark' => 'Bookmark',
  'icon-briefcase' => 'Briefcase',
  'icon-bullhorn' => 'Bullhorn',
  'icon-calendar' => 'Calendar',
  'icon-camera' => 'Camera',
  'icon-certificate' => 'Certificate',
  'icon-check' => 'Check',
  'icon-chevron-down' => 'chevron-down',
  'icon-chevron-left' => 'Chevron-left',
  'icon-chevron-right' => 'Chevron-right',
  'icon-chevron-up' => 'chevron-up',
  'icon-circle-arrow-down' => 'Circle-arrow-down',
  'icon-circle-arrow-left' => 'Circle-arrow-left',
  'icon-circle-arrow-right' => 'Circle-arrow-right',
  'icon-circle-arrow-up' => 'Circle-arrow-up',
  'icon-cog' => 'Cog',
  'icon-comment' => 'Comment',
  'icon-download' => 'Download',
  'icon-download-alt' => 'Download-alt',
  'icon-edit' => 'Edit',
  'icon-eject' => 'Eject',
  'icon-envelope' => 'Envelope',
  'icon-exclamation-sign' => 'Exclamation-sign',
  'icon-eye-close' => 'Eye-close',
  'icon-eye-open' => 'Eye-open',
  'icon-facetime-video' => 'Facetime-video',
  'icon-fast-backward' => 'Fast-backward',
  'icon-fast-forward' => 'Fast-forward',
  'icon-file' => 'File',
  'icon-film' => 'Film',
  'icon-filter' => 'Filter',
  'icon-fire' => 'Fire',
  'icon-flag' => 'Flag',
  'icon-folder-close' => 'Folder-close',
  'icon-folder-open' => 'Folder-open',
  'icon-font' => 'Font',
  'icon-forward' => 'Forward',
  'icon-fullscreen' => 'Fullscreen',
  'icon-gift' => 'Gift',
  'icon-glass' => 'Glass',
  'icon-globe' => 'Globe',
  'icon-hand-down' => 'Hand-down',
  'icon-hand-left' => 'Hand-left',
  'icon-hand-right' => 'Hand-right',
  'icon-hand-up' => 'Hand-up',
  'icon-hdd' => 'Hdd',
  'icon-headphones' => 'Headphones',
  'icon-heart' => 'Heart',
  'icon-home' => 'Home',
  'icon-inbox' => 'Inbox',
  'icon-indent-left' => 'Indent-left',
  'icon-indent-right' => 'Indent-right',
  'icon-info-sign' => 'Info-sign',
  'icon-italic' => 'Italic',
  'icon-leaf' => 'Leaf',
  'icon-list' => 'List',
  'icon-list-alt' => 'List-alt',
  'icon-lock' => 'Lock',
  'icon-magnet' => 'Magnet',
  'icon-map-marker' => 'Map-marker',
  'icon-minus' => 'Minus',
  'icon-minus-sign' => 'Minus-sign',
  'icon-move' => 'Move',
  'icon-music' => 'Music',
  'icon-off' => 'Off',
  'icon-ok' => 'Ok',
  'icon-ok-circle' => 'Ok-circle',
  'icon-ok-sign' => 'Ok-sign',
  'icon-pause' => 'Pause',
  'icon-pencil' => 'Pencil',
  'icon-picture' => 'Picture',
  'icon-plane' => 'Plane',
  'icon-play' => 'Play',
  'icon-play-circle' => 'Play-circle',
  'icon-plus' => 'Plus',
  'icon-plus-sign' => 'Plus-sign',
  'icon-print' => 'Print',
  'icon-qrcode' => 'Qrcode',
  'icon-question-sign' => 'Question-sign',
  'icon-random' => 'Random',
  'icon-refresh' => 'Refresh',
  'icon-remove' => 'Remove',
  'icon-remove-circle' => 'Remove-circle',
  'icon-remove-sign' => 'Remove-sign',
  'icon-repeat' => 'Repeat',
  'icon-resize-full' => 'Resize-full',
  'icon-resize-horizontal' => 'Resize-horizontal',
  'icon-resize-small' => 'Resize-small',
  'icon-resize-vertical' => 'Resize-vertical',
  'icon-retweet' => 'retweet',
  'icon-road' => 'Road',
  'icon-screenshot' => 'Screenshot',
  'icon-search' => 'Search',
  'icon-share' => 'Share',
  'icon-share-alt' => 'Share-alt',
  'icon-shopping-cart' => 'Shopping-cart',
  'icon-signal' => 'Signal',
  'icon-star' => 'Star',
  'icon-star-empty' => 'Star-empty',
  'icon-step-backward' => 'Step-backward',
  'icon-step-forward' => 'Step-forward',
  'icon-stop' => 'Stop',
  'icon-tag' => 'Tag',
  'icon-tags' => 'Tags',
  'icon-tasks' => 'Tasks',
  'icon-text-height' => 'Text-height',
  'icon-text-width' => 'Text-width',
  'icon-th' => 'th',
  'icon-th-large' => 'th-large',
  'icon-th-list' => 'th-list',
  'icon-thumbs-down' => 'Thumbs-down',
  'icon-thumbs-up' => 'Thumbs-up',
  'icon-time' => 'Time',
  'icon-tint' => 'Tint',
  'icon-trash' => 'Trash',
  'icon-upload' => 'Upload',
  'icon-user' => 'User',
  'icon-volume-down' => 'Volume-down',
  'icon-volume-off' => 'Volume-off',
  'icon-volume-up' => 'Volume-up',
  'icon-warning-sign' => 'Warning-sign',
  'icon-wrench' => 'Wrench',
  'icon-zoom-in' => 'Zoom-in',
  'icon-zoom-out' => 'Zoom-out',
);
?>
<div class="row-fluid " <?php echo (isset($element_param['display'])?($element_param['display']=="none"?'style="display:none;"':''):'');?>>
	<div class="yee-setting-heading"><strong><?php echo $element_param['heading'];?></strong></div>
	<div class="yee-setting-value">
		<select style="width:100%" name="<?php echo $element_param['param_name'];?>" <?php echo $type_attrbute;?>>
			<?php foreach($option_value as $key=>$value){?>
				     <option value="<?php echo $key;?>" <?php echo ($element_param['value']==$key?'selected="selected"':'');?>><?php echo $value;?></option>
			<?php }?>
		</select>
	</div>
	<div class="yee-setting-description"><?php echo $element_param['description'];?></div>
</div>	
